pos/myapp/urls.py
from django.urls import path
from .views import *
from . import views
app_name = 'myapp'
urlpatterns = [
	path('', views.testfile, name='testfile'),
	#sale
	path('inv_list/', views.inv_list, name='inv_list'),
	path('detail_inv/<int:id>/', views.detail_inv, name='detail_inv'),
	path('create_invoice/', views.create_invoice, name='create_invoice'),
	path('itm_add_invitm/', views.itm_add_invitm, name='itm_add_invitm'),
	path('print_preview/<int:id>/', views.print_preview, name='print_preview'),

	# setup menu
	path('itemlist/', views.itemlist, name='itemlist'),

	#reports
]

pos/pos/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    # path('e/', include('employee.urls')),
    # path('w/', include('webview.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pos/myapp/models.py
from django.db import models

# Create your models here.
# Create your models here.
class item(models.Model):
    photo = models.ImageField(upload_to='', blank=True, null=True)
    item_name = models.CharField(max_length=255)
    slug = models.CharField(max_length=255, blank=True, null=True)
    price = models.PositiveIntegerField(default=0)
    stock = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.item_name


class invoice_heading(models.Model):
    photo = models.ImageField(upload_to='', blank=True, null=True)
    description = models.CharField(max_length=255, blank=True, null=True)


class invoice(models.Model):
    customer = models.CharField(max_length=255, blank=True, null=True)
    total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.id}"

class invitem(models.Model):
    inv = models.ForeignKey(invoice, on_delete=models.CASCADE)
    item = models.CharField(max_length=255)
    qty = models.PositiveIntegerField(default=0)
    rate = models.PositiveIntegerField(default=0)
    amount = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.item

pos/myapp/views.py
from django.shortcuts import render,redirect
from django.http import JsonResponse
from .models import *
# Create your views here.
def testfile(request):
	return render(request, 'test.html')


# Setup Menu 
def itemlist(request):
    itm = item.objects.all()
    context = {'itm':itm}
    return render(request, 'itemlist.html', context)






def inv_list(request):
	inv = invoice.objects.all().order_by('-id')
	context = {'inv':inv}
	return render(request, 'inv_list.html', context)

def detail_inv(request, id):
    # dictionary for initial data with 
    # field names as keys
    context ={}
 
    # add the dictionary during initialization
    context["invitm"] = invitem.objects.filter(inv=id)
    context["data"] = invoice.objects.get(id = id)
    context["itm"] = item.objects.all()
         
    return render(request, "detail_inv.html", context)




def create_invoice(request):
    cu = request.GET.get('cu')
    inv_obj = invoice.objects.create(customer=cu, total=0)
    return JsonResponse({'status':'success'})

# {itm:itm, ipri:ipri, iqty:iqty},
def itm_add_invitm(request):
    itm = request.GET.get('itm')
    ipri = request.GET.get('ipri')
    iqty = request.GET.get('iqty')
    invid = request.GET.get('invid')
    r = int(ipri)
    qty = int(iqty)
    am = int(r * qty)
    # print(am)
    inv_obj = invoice.objects.get(id = int(invid))
    i = invitem(inv=inv_obj, item=itm, qty=qty, rate=r, amount=am)
    i.save()
    inv_obj.total += am
    inv_obj.save()
    return JsonResponse({'status':'success'})


def print_preview(request,id):
    context ={}
 
    # add the dictionary during initialization
    context["invitm"] = invitem.objects.filter(inv=id)
    context["data"] = invoice.objects.get(id = id)
    context["p"] = invoice_heading.objects.get(id=1)
     
    return render(request, "print_preview.html", context)
    

pos/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <!-- DataTable -->
<link rel="stylesheet" href="https://cdn.datatables.net/2.0.7/css/dataTables.dataTables.css" />

    <!-- <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/autofill/2.7.0/css/autoFill.bootstrap4.min.css"> -->

    <title></title>
  </head>
  <body>
  	<nav class="navbar navbar-expand-lg navbar-light bg-info">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link text-white" href="#">ပင်မစာမျက်နှာ <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-white" href="{% url 'myapp:inv_list' %}">အရောင်းဘောက်ချာများ</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
          Setup
        </a>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="{% url 'myapp:itemlist' %}">Create Item</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
  </div>
</nav>
    <!-- <h1>Hello, world!</h1> -->

   
<!-- Jumbotron -->

    <div class="jumbotron jumbotron-fluid">
  <div class="container-fluid">
    
{% block content %}
{% endblock content %}

  </div>
</div>

<!-- End Jumbotron -->




    <!-- Option 2: Separate Popper and Bootstrap JS -->
    
    <!-- <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script> -->
    <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    

  
<script src="https://cdn.datatables.net/2.0.7/js/dataTables.js"></script>

<!-- <script type="text/javascript" src="https://cdn.datatables.net/autofill/2.7.0/js/dataTables.autoFill.min.js"></script>

<script type="text/javascript" src="https://cdn.datatables.net/autofill/2.7.0/js/autoFill.bootstrap4.min.js"></script> -->


<script>
  
$(document).ready(function(){
  // start new invoice and customer
$("#createCus").on('click', '.invModal', function() {
  
  var cu = $("#cusName").val();
  // console.log(cu);
  $.ajax({
    url: "/create_invoice/",
    method: "GET",
    data:{cu:cu,},
    success: function(data){
        // console.log(data.status);

        // alert('Item Add Successfully');
        window.setTimeout(function(){ } ,2000);
                        location.reload();

        // window.location.href = '/admin/';
        // window.open('https://www.codexworld.com', '_blank');
    },
    error:function(){
        alert('having some error contact to developer');
    },
                    
  });//end ajax

});//end new invoice and customer


//start add item to invoice 

$("#modalItmCard").on('click', '.addItem', function() {
  
  var currentRow = $(this).closest(".card");
  var itm = currentRow.find(".itmname").html();
  var ipri = currentRow.find(".iprice").html();
  var iqty = currentRow.find("input").val(); 
  // console.log(iqty);
  var invid = $("#invid").html();
  // alert(invid);
  $.ajax({
    url: "/itm_add_invitm/",
    method: "GET",
    data:{itm:itm, ipri:ipri, iqty:iqty, invid:invid},
    success: function(data){
        // console.log(data.status);

        // alert('Item Add Successfully');
        window.setTimeout(function(){ } ,2000);
                        location.reload();

        // window.location.href = '/admin/';
        // window.open('https://www.codexworld.com', '_blank');
    },
    error:function(){
        alert('having some error contact to developer');
    },
                    
  });//end ajax


});//end add item to invoice 


// $(document).ready( function () {
//     $('#myTable').DataTable();
// } );




});



</script>


<script type="text/javascript">
  $(document).ready( function () {
    $('#itemlisttable').DataTable();
} );


</script>

  </body>
</html>

pos/templates/detail_inv.html
{% extends 'base.html' %}

{% block content %}


<!-- {{data.id}}
{{data.customer}} -->


<div class="card border-info mb-3">
  <div class="card-body">

<!-- Button to Open the Modal -->
  

<span id="invid" hidden>{{data.id}}</span>
<hr>
<div class="row">
  <div class="col-md-6"><h3>Customer Name : {{data.customer}}</h3></div>
  <div class="col-md-6">
    <button type="button" class="btn btn-success btn-block" data-toggle="modal" data-target="#myModal">
     + Open Item List
  </button>
  </div>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">စဉ် </th>
      <th scope="col">အမျိုးအမည် </th>
      <th scope="col">ဦးရေ </th>
      <th scope="col">နှုန်း  </th>
      <th scope="col">ကျပ် </th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
  	{% for i in invitm %}
    <tr>
      <th scope="row">{{forloop.counter}}</th>
      <td>{{i.item}}</td>
      <td>{{i.qty}}</td>
      <td>{{i.rate}}</td>
      <td class="text-right">
      	{{i.amount}}
      </td>
      <td>
        <button class="btn btn-sm btn-outline-danger rmvItem">X</button>
      </td>
    </tr>
    {% endfor %}

    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td>Total</td>
      <td class="text-right"><strong>{{data.total}}</strong></td>
      <td></td>
    </tr>

    <tr>
    	<td></td>
    	
    	<td colspan="3">
    		<!-- <button type="button" class="btn btn-success btn-block" data-toggle="modal" data-target="#myModal">
    Open Item List
  </button> -->
    	</td>
    	<td></td>
      <td></td>

    </tr>
    
  </tbody>
</table>


  <!-- The Modal -->
  <div class="modal fade" id="myModal">
    <div class="modal-dialog modal-xl">
      <div class="modal-content">
      
        <!-- Modal Header -->
        <div class="modal-header">
          <h4 class="modal-title">Modal Heading</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        
        <!-- Modal body -->
        <div class="modal-body"  id="modalItmCard">
          
<div class="row">
{% for i in itm %}
<div class="col-md-3 mb-30">
	<div class="card" style="width: 15rem;">
  <img class="card-img-top" src="{{i.photo.url}}" alt="cap" height="120px">
  <div class="card-body">
    <h5 class="card-title itmname">{{i.item_name}}</h5>
    <span class="text-primary iprice">{{i.price}}</span>

    <p class="card-text">
    	
    	<input type="number" class="form-control" placeholder="Enter Qty">
    </p>
    <!-- <a href="#" class="btn btn-primary">Go somewhere</a> -->
    <button class="btn btn-info btn-block addItem">Add Item</button>
  </div>
</div>
</div>
{% endfor %}
</div> <!-- row end -->

  








        </div>
        
        <!-- Modal footer -->
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
        
      </div>
    </div>
  </div>

  </div>
</div>






{% endblock content %}

pos/templates/inv_list.html
{% extends 'base.html' %}

{% block content %}


<div class="card border-info mb-3">
  <div class="card-body">

<!-- Button trigger modal -->
<button type="button" class="btn btn-success" data-toggle="modal" data-target="#createNewInv">
  + Create New Invoice
</button>

<!-- Modal -->
<div class="modal fade" id="createNewInv" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content" id="createCus">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Enter Customer</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <input type="text" name="newCustomer" class="form-control" id="cusName">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-success invModal">Create Invoice</button>
      </div>
    </div>
  </div>
</div>

<hr>

<table class="table table-striped" id="invlist">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Customer Name</th>
      <th scope="col">Amount</th>
      <th scope="col">Date</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
  	{% for i in inv %}
    <tr>
      <th scope="row">{{i.id}}</th>
      <td>{{i.customer}}</td>

      <td>{{i.total}}</td>
      <td>{{i.created_at}}</td>
      <td>
      	<a href="{% url 'myapp:detail_inv' i.id %}" class="btn btn-sm btn-outline-success">Add Items</a>
      	<a href="{% url 'myapp:print_preview' i.id %}" class="btn btn-sm btn-outline-info">Print</a>
      </td>
    </tr>
    {% endfor %}
    
  </tbody>
</table>



  </div>
</div>




{% endblock content %}

pos/templates/itemlist.html
{% extends 'base.html' %}

{% block content %}


<div class="card border-info mb-3">
  <div class="card-body">

<!-- Button trigger modal -->
<button type="button" class="btn btn-success" data-toggle="modal" data-target="#createItm">
  + Create New Item
</button>

<!-- Modal -->
<div class="modal fade" id="createItm" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content" id="createCus">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Enter Customer</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <input type="text" name="newCustomer" class="form-control" id="cusName">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-success invModal">Create Invoice</button>
      </div>
    </div>
  </div>
</div>

<hr>

<table class="table table-striped" id="itemlisttable">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">item_name</th>
      <th scope="col">price</th>
      <th scope="col">stock</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
  	{% for i in itm %}
    <tr>
      <th scope="row"><img src="{{i.photo.url}}" width="60px"></th>
      <td>{{i.item_name}}</td>

      <td>{{i.price}}</td>
      <td>{{i.stock}}</td>
      <td>
      	<a href="#">update</a>
      </td>
    </tr>
    {% endfor %}
    
  </tbody>
</table>



  </div>
</div>



{% endblock content %}

pos/templates/print_preview.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title></title>
  <style>
     * {
    font-size: 12px;
    font-family: 'Times New Roman';
}

td,
th,
tr,
table {
    border: 1px solid black;

    border-collapse: collapse;
    height: 50px;
}





    .cusName{
      color: red;
      font-size: 20px;
      font-weight: bold;
    }
    .dte{
      color: red;
      font-size: 20px;
      font-weight: bold;
      margin-left: 500px;
    }

.srno{
  width: 50px;
  max-width: 50px;
  text-align: center;
  font-size: 22px;
}


.itmname, .titm{
   width: 800px;
    max-width: 800px;
    text-align: center;
    align-content: center;
    font-size : 22px;
    font-weight: bold;
}

.hqty, .tqty{
  width: 80px;
    max-width: 80px;
    text-align: center;
    align-content: center;
    font-size : 18px;
}

.hrate, .trate{
  width: 150px;
    max-width: 150px;
    text-align: center;
    align-content: center;
    font-size : 18px;
}

.amt, .tamt{
   width: 200px;
    max-width: 200px;
    text-align: center;
    align-content: center;
    font-size : 18px;
}




  </style>
</head>
<body>





{{data.id}}

<img src="{{p.photo.url}}" width="100%">

<div>
  <span class="cusName">ဝယ်သူအမည် : ----</span> <span class="dte">ရက်စွဲ : </span>
</div>



<div>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col" class="srno">စဉ် </th>
      <th scope="col" class="itmname">အမျိုးအမည် </th>
      <th scope="col" class="hqty">ဦးရေ </th>
      <th scope="col" class="hrate">နှုန်း  </th>
      <th scope="col" class="amt">ကျပ် </th>
      
    </tr>
  </thead>
  <tbody>
    {% for i in invitm %}
    <tr>
      <th scope="row">{{forloop.counter}}</th>
      <td class="titm">{{i.item}}</td>
      <td class="tqty">{{i.qty}}</td>
      <td class="trate">{{i.rate}}</td>
      <td class="tamt">
        {{i.amount}}
      </td>
      
    </tr>
    {% endfor %}

    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td>Total</td>
      <td class="text-right"><strong>{{data.total}}</strong></td>
      
    </tr>

    <tr>
      <td></td>
      
      <td colspan="3">
        
      </td>
      <td></td>
      

    </tr>
    
  </tbody>
</table>

</div>






</body>
</html>

pos/templates/test.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
  	<nav class="navbar navbar-expand-lg navbar-light bg-info">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
          Dropdown link
        </a>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
  </div>
</nav>
    <!-- <h1>Hello, world!</h1> -->

<!-- Jumbotron -->

    <div class="jumbotron jumbotron-fluid">
  <div class="container-fluid">
    <div class="card border-info mb-3">
  <div class="card-body">


<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  Launch demo modal
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>







    <form>
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1">
  </div>
  <div class="form-group form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Check me out</label>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
  </div>
</div>
  </div>
</div>

<!-- End Jumbotron -->

   
<!-- Jumbotron -->

    <div class="jumbotron jumbotron-fluid">
  <div class="container-fluid">
    <div class="card border-info mb-3">
  <div class="card-body">

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">First</th>
      <th scope="col">Last</th>
      <th scope="col">Handle</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Mark</td>
      <td>Otto</td>
      <td>@mdo</td>
    </tr>
    <tr>
      <th scope="row">2</th>
      <td>Jacob</td>
      <td>Thornton</td>
      <td>@fat</td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td>Larry</td>
      <td>the Bird</td>
      <td>@twitter</td>
    </tr>
  </tbody>
</table>



  </div>
</div>
  </div>
</div>

<!-- End Jumbotron -->




    <!-- Option 2: Separate Popper and Bootstrap JS -->
    
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    
  </body>
</html>